# TCL File Generated by Component Editor 18.0
# Thu Jun 27 14:50:37 BRT 2019
# DO NOT MODIFY


# 
# lcd_controller "lcd_controller" v1.0
#  2019.06.27.14:50:37
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module lcd_controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME lcd_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME lcd_controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL LCD_Controll
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file LCD_Controll.v VERILOG PATH ../LCD_Controll.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter M_LED1 STD_LOGIC_VECTOR 0
set_parameter_property M_LED1 DEFAULT_VALUE 0
set_parameter_property M_LED1 DISPLAY_NAME M_LED1
set_parameter_property M_LED1 WIDTH 5
set_parameter_property M_LED1 TYPE STD_LOGIC_VECTOR
set_parameter_property M_LED1 ENABLED false
set_parameter_property M_LED1 UNITS None
set_parameter_property M_LED1 ALLOWED_RANGES 0:31
set_parameter_property M_LED1 HDL_PARAMETER true
add_parameter M_LED2 STD_LOGIC_VECTOR 1
set_parameter_property M_LED2 DEFAULT_VALUE 1
set_parameter_property M_LED2 DISPLAY_NAME M_LED2
set_parameter_property M_LED2 WIDTH 5
set_parameter_property M_LED2 TYPE STD_LOGIC_VECTOR
set_parameter_property M_LED2 ENABLED false
set_parameter_property M_LED2 UNITS None
set_parameter_property M_LED2 ALLOWED_RANGES 0:31
set_parameter_property M_LED2 HDL_PARAMETER true
add_parameter M_LED3 STD_LOGIC_VECTOR 2
set_parameter_property M_LED3 DEFAULT_VALUE 2
set_parameter_property M_LED3 DISPLAY_NAME M_LED3
set_parameter_property M_LED3 WIDTH 5
set_parameter_property M_LED3 TYPE STD_LOGIC_VECTOR
set_parameter_property M_LED3 ENABLED false
set_parameter_property M_LED3 UNITS None
set_parameter_property M_LED3 ALLOWED_RANGES 0:31
set_parameter_property M_LED3 HDL_PARAMETER true
add_parameter M_LED4 STD_LOGIC_VECTOR 3
set_parameter_property M_LED4 DEFAULT_VALUE 3
set_parameter_property M_LED4 DISPLAY_NAME M_LED4
set_parameter_property M_LED4 WIDTH 5
set_parameter_property M_LED4 TYPE STD_LOGIC_VECTOR
set_parameter_property M_LED4 ENABLED false
set_parameter_property M_LED4 UNITS None
set_parameter_property M_LED4 ALLOWED_RANGES 0:31
set_parameter_property M_LED4 HDL_PARAMETER true
add_parameter M_LED5 STD_LOGIC_VECTOR 4
set_parameter_property M_LED5 DEFAULT_VALUE 4
set_parameter_property M_LED5 DISPLAY_NAME M_LED5
set_parameter_property M_LED5 WIDTH 5
set_parameter_property M_LED5 TYPE STD_LOGIC_VECTOR
set_parameter_property M_LED5 ENABLED false
set_parameter_property M_LED5 UNITS None
set_parameter_property M_LED5 ALLOWED_RANGES 0:31
set_parameter_property M_LED5 HDL_PARAMETER true
add_parameter L_LED1 STD_LOGIC_VECTOR 5
set_parameter_property L_LED1 DEFAULT_VALUE 5
set_parameter_property L_LED1 DISPLAY_NAME L_LED1
set_parameter_property L_LED1 WIDTH 5
set_parameter_property L_LED1 TYPE STD_LOGIC_VECTOR
set_parameter_property L_LED1 ENABLED false
set_parameter_property L_LED1 UNITS None
set_parameter_property L_LED1 ALLOWED_RANGES 0:31
set_parameter_property L_LED1 HDL_PARAMETER true
add_parameter L_LED2 STD_LOGIC_VECTOR 6
set_parameter_property L_LED2 DEFAULT_VALUE 6
set_parameter_property L_LED2 DISPLAY_NAME L_LED2
set_parameter_property L_LED2 WIDTH 5
set_parameter_property L_LED2 TYPE STD_LOGIC_VECTOR
set_parameter_property L_LED2 ENABLED false
set_parameter_property L_LED2 UNITS None
set_parameter_property L_LED2 ALLOWED_RANGES 0:31
set_parameter_property L_LED2 HDL_PARAMETER true
add_parameter L_LED3 STD_LOGIC_VECTOR 7
set_parameter_property L_LED3 DEFAULT_VALUE 7
set_parameter_property L_LED3 DISPLAY_NAME L_LED3
set_parameter_property L_LED3 WIDTH 5
set_parameter_property L_LED3 TYPE STD_LOGIC_VECTOR
set_parameter_property L_LED3 ENABLED false
set_parameter_property L_LED3 UNITS None
set_parameter_property L_LED3 ALLOWED_RANGES 0:31
set_parameter_property L_LED3 HDL_PARAMETER true
add_parameter L_LED4 STD_LOGIC_VECTOR 8
set_parameter_property L_LED4 DEFAULT_VALUE 8
set_parameter_property L_LED4 DISPLAY_NAME L_LED4
set_parameter_property L_LED4 WIDTH 5
set_parameter_property L_LED4 TYPE STD_LOGIC_VECTOR
set_parameter_property L_LED4 ENABLED false
set_parameter_property L_LED4 UNITS None
set_parameter_property L_LED4 ALLOWED_RANGES 0:31
set_parameter_property L_LED4 HDL_PARAMETER true
add_parameter L_LED5 STD_LOGIC_VECTOR 9
set_parameter_property L_LED5 DEFAULT_VALUE 9
set_parameter_property L_LED5 DISPLAY_NAME L_LED5
set_parameter_property L_LED5 WIDTH 5
set_parameter_property L_LED5 TYPE STD_LOGIC_VECTOR
set_parameter_property L_LED5 ENABLED false
set_parameter_property L_LED5 UNITS None
set_parameter_property L_LED5 ALLOWED_RANGES 0:31
set_parameter_property L_LED5 HDL_PARAMETER true
add_parameter ESCREVE STD_LOGIC_VECTOR 0
set_parameter_property ESCREVE DEFAULT_VALUE 0
set_parameter_property ESCREVE DISPLAY_NAME ESCREVE
set_parameter_property ESCREVE WIDTH 5
set_parameter_property ESCREVE TYPE STD_LOGIC_VECTOR
set_parameter_property ESCREVE ENABLED false
set_parameter_property ESCREVE UNITS None
set_parameter_property ESCREVE ALLOWED_RANGES 0:31
set_parameter_property ESCREVE HDL_PARAMETER true
add_parameter LIMPAR STD_LOGIC_VECTOR 1
set_parameter_property LIMPAR DEFAULT_VALUE 1
set_parameter_property LIMPAR DISPLAY_NAME LIMPAR
set_parameter_property LIMPAR WIDTH 5
set_parameter_property LIMPAR TYPE STD_LOGIC_VECTOR
set_parameter_property LIMPAR ENABLED false
set_parameter_property LIMPAR UNITS None
set_parameter_property LIMPAR ALLOWED_RANGES 0:31
set_parameter_property LIMPAR HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock ""
set_interface_property avalon_slave_0 associatedReset ""
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 clock_50MHz beginbursttransfer Input 1
add_interface_port avalon_slave_0 entrada writedata Input 32
add_interface_port avalon_slave_0 LCD_RS writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 LCD_EN writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 LCD_RW writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 LCD_D readdata Output 8
add_interface_port avalon_slave_0 LEDM_C readdata Output 5
add_interface_port avalon_slave_0 LEDM_R readdata Output 8
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0

